version: '3'

services:
  python:
    build: .
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s
    container_name: python
    command: 'python main.py'
    ports:
     - "8000:8000"
    depends_on:
     - db
    volumes:
      - .:/var/www/app/
    networks:
      - tcc-network

  db:
    build: ./init/mysql
    container_name: tccmysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
     - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./init/mysql/dbdata:/var/lib/mysql
    networks:
      - tcc-network

networks:
  tcc-network:
    driver: bridge

